name: CeleryUtils
version: ${project.version}
main: xyz.qincai.celeryutils.CeleryUtils
description: ${project.description}
authors:
  - QinCai-rui
website: https://github.com/QinCai-rui/Celery-Utils

api-version: 1.21

softdepend:
  - Vault

commands:
  celeryutils:
    description: Main command for CeleryUtils
    usage: /celeryutils <subcommand>
    aliases: [cu]


permissions:
  celeryutils.pvp:
    description: Allow starting a PvP session
    default: op
  celeryutils.admin:
    description: Admin access to CeleryUtils
    default: op
  celeryutils.discordlink:
    description: Permission for Discord Link module
    default: op
  celeryutils.economy:
    description: Permission for Economy Permissions module
    default: op
  celeryutils.killall:
    description: Permission to run /killall
    default: op
  celeryutils.tempban:
    description: Permission to run /tempban
    default: op
  celeryutils.kickall:
    description: Permission to run /kickall
    default: op
  celeryutils.gamemode:
    description: Permission to use /gm
    default: op
  celeryutils.tips:
    description: Permission to use /tips
    default: true
